// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_LDAP_LDAP_H
#define ANALYZER_PROTOCOL_LDAP_LDAP_H

#include "analyzer/protocol/tcp/TCP.h"
#include "events.bif.h"
#include "ldap_pac.h"

namespace analyzer { namespace LDAP {

class LDAP_Analyzer : public tcp::TCP_ApplicationAnalyzer {

typedef struct {
	unsigned char *ldap_buf;
	int64_t ldap_buf_len;
	int64_t processed_len;
	bool building_packet;
} Endpoint;

public:
	LDAP_Analyzer(zeek::Connection* conn);
	~LDAP_Analyzer() override;

	// Overriden from Analyzer.
	void Done() override;

	void DeliverStream(int len, const u_char* data, bool orig) override;
	void Undelivered(uint64_t seq, int len, bool orig) override;

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	void EndpointEOF(bool is_orig) override;

	static zeek::analyzer::Analyzer* InstantiateAnalyzer(zeek::Connection* conn)
		{ return new LDAP_Analyzer(conn); }

protected:
	binpac::LDAP::LDAP_Conn* interp;
	bool had_gap;
	int packet_counter;

	Endpoint endp_orig;
	Endpoint endp_resp;
};

} } // namespace analyzer::*

#endif
