// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "LDAP.h"

namespace plugin {
namespace Zeek_LDAP {

class Plugin : public plugin::Plugin {
public:
	zeek::plugin::Configuration Configure()
		{
		AddComponent(new zeek::analyzer::Component("LDAP",
		             ::analyzer::LDAP::LDAP_Analyzer::InstantiateAnalyzer));

		zeek::plugin::Configuration config;
		config.name = "Zeek::LDAP";
		config.description = "Lightweight Directory Access Protocol analyzer";
		return config;
		}
} plugin;

}
}